(function () {
  function buildUniversalHeader() {
    if (document.querySelector('.sw7-universal-header')) return;
    var sourceLogo = document.querySelector('.brand-logo img, header img.logo, .topbar img.logo, img.logo');
    var header = document.createElement('header');
    header.className = 'sw7-universal-header';
    var brand = document.createElement('a');
    brand.className = 'sw7-universal-brand'; brand.href = 'index.html';
    if (sourceLogo) { var logo = sourceLogo.cloneNode(true); logo.removeAttribute('class'); logo.removeAttribute('style'); brand.appendChild(logo); }
    var name = document.createElement('span'); name.textContent = 'StartWeb7'; brand.appendChild(name);
    var nav = document.createElement('nav'); nav.className = 'sw7-clean-nav';
    nav.innerHTML = '<a href="index.html">Home</a><a href="about.html">About</a><div class="sw7-clean-item sw7-services-item"><a href="services.html">Services</a><button type="button">›</button><div class="sw7-clean-menu sw7-services-menu"><div class="sw7-clean-sub"><button type="button" class="website">WEBSITE DESIGN <b>›</b></button><div class="sw7-clean-submenu"><a href="landing-page.html">LANDING PAGE</a><a href="multi-page-website.html">MULTI-PAGE WEBSITE</a><a href="seo-optimized-website.html">SEO-OPTIMIZED WEBSITE</a></div></div><div class="sw7-clean-sub"><button type="button" class="seo">SEO + AEO MANAGEMENT <b>›</b></button><div class="sw7-clean-submenu"><a href="seo-aeo-management.html">SEO MANAGEMENT</a><a href="essentials.html">ESSENTIALS</a><a href="competitive.html">COMPETITIVE</a></div></div></div></div><a href="reviews.html">Reviews</a><a href="faq.html">FAQ</a><div class="sw7-clean-item sw7-contact-item"><a href="contact.html">Contact</a><button type="button">›</button><div class="sw7-clean-menu sw7-contact-menu"><a href="contact.html">CONTACT</a><a href="support.html">24/7 SUPPORT</a><a href="careers.html">CAREERS</a></div></div>';
    document.querySelectorAll('header, nav, .topbar').forEach(function (oldHeader) { oldHeader.classList.add('sw7-original-header-hidden'); });
    header.appendChild(brand); header.appendChild(nav); document.body.insertBefore(header, document.body.firstChild);
    header.querySelectorAll('.sw7-clean-item > button,.sw7-clean-sub > button').forEach(function (button) { button.addEventListener('click', function (event) { event.stopPropagation(); button.parentElement.classList.toggle('open'); }); });
    document.addEventListener('click', function () { header.querySelectorAll('.open').forEach(function (item) { item.classList.remove('open'); }); });
    var style = document.createElement('style');
    style.textContent = `
body{padding-top:78px!important}.sw7-original-header-hidden{display:none!important;height:0!important;min-height:0!important;margin:0!important;padding:0!important;overflow:hidden!important}
.sw7-universal-header{position:fixed!important;z-index:2147483000!important;top:0!important;left:0!important;right:0!important;height:78px!important;background:#fff!important;color:#111!important;display:flex!important;align-items:center!important;justify-content:space-between!important;padding:0 max(24px,calc((100vw - 1120px)/2))!important;box-sizing:border-box!important;box-shadow:0 1px 0 rgba(0,0,0,.08)!important}
.sw7-universal-brand{display:flex!important;align-items:center!important;gap:13px!important;color:#111!important;text-decoration:none!important;white-space:nowrap!important;flex:0 0 auto!important}.sw7-universal-brand img{display:block!important;width:112px!important;height:58px!important;object-fit:contain!important}.sw7-universal-brand span{font:900 17px/1 Arial,Helvetica,sans-serif!important;letter-spacing:.04em!important}
.sw7-clean-nav{display:flex!important;width:660px!important;height:78px!important;align-items:center!important;justify-content:space-between!important;gap:0!important;margin:0 0 0 auto!important;padding:0!important;background:transparent!important;overflow:visible!important}.sw7-clean-nav>a,.sw7-clean-item{display:flex!important;align-items:center!important;justify-content:center!important;height:78px!important;margin:0!important;padding:0!important;flex:0 0 auto!important;position:relative!important}.sw7-clean-nav>a,.sw7-clean-item>a{font:500 13px/1 Arial,Helvetica,sans-serif!important;color:#111!important;text-decoration:none!important;white-space:nowrap!important}.sw7-clean-item>button{appearance:none!important;border:0!important;background:transparent!important;color:#111!important;font:500 17px/1 Arial!important;margin-left:5px!important;padding:4px!important;cursor:pointer!important}
.sw7-clean-menu{position:absolute!important;z-index:2147483001!important;top:64px!important;min-width:270px!important;padding:10px!important;background:#f4f3ef!important;color:#111!important;box-shadow:0 20px 50px rgba(0,0,0,.2)!important;opacity:0!important;visibility:hidden!important;transform:translateY(8px)!important;transition:.2s ease!important;text-align:left!important}.sw7-services-menu{left:0!important}.sw7-contact-menu{right:0!important;min-width:210px!important}.sw7-clean-item:hover>.sw7-clean-menu,.sw7-clean-item:focus-within>.sw7-clean-menu,.sw7-clean-item.open>.sw7-clean-menu{opacity:1!important;visibility:visible!important;transform:none!important}
.sw7-clean-menu a,.sw7-clean-sub>button{display:flex!important;align-items:center!important;justify-content:space-between!important;width:100%!important;margin:0!important;padding:13px 14px!important;border:0!important;background:transparent!important;color:#111!important;text-decoration:none!important;font:800 12px/1.2 Arial!important;letter-spacing:.04em!important;box-sizing:border-box!important;white-space:normal!important;cursor:pointer!important}.sw7-clean-menu a:hover,.sw7-clean-sub>button:hover{background:#fff!important}.sw7-clean-sub{position:relative!important}.sw7-clean-sub>button.website{color:#0784ff!important;border-left:4px solid #0784ff!important}.sw7-clean-sub>button.seo{color:#00a978!important;border-left:4px solid #00a978!important}.sw7-clean-submenu{position:absolute!important;left:100%!important;top:-10px!important;min-width:275px!important;padding:10px!important;background:#fff!important;box-shadow:0 20px 50px rgba(0,0,0,.18)!important;opacity:0!important;visibility:hidden!important;transform:translateX(8px)!important;transition:.2s ease!important}.sw7-clean-sub:hover>.sw7-clean-submenu,.sw7-clean-sub:focus-within>.sw7-clean-submenu,.sw7-clean-sub.open>.sw7-clean-submenu{opacity:1!important;visibility:visible!important;transform:none!important}
@media(max-width:900px){.sw7-universal-brand span{display:none!important}.sw7-universal-brand img{width:82px!important}.sw7-universal-header{padding:0 16px!important;overflow-x:auto!important}.sw7-clean-nav{width:max-content!important;justify-content:flex-start!important;gap:22px!important;margin-left:22px!important}.sw7-clean-submenu{position:static!important;display:none!important;opacity:1!important;visibility:visible!important;transform:none!important;box-shadow:none!important}.sw7-clean-sub.open>.sw7-clean-submenu{display:block!important}}`;
    document.head.appendChild(style);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', buildUniversalHeader); else buildUniversalHeader();
})();
